#!/usr/bin/with-contenv bash

if [ "${WARP_ENABLED}" = "true" ]; then
  if [ ! -e "/config/wgcf-account.toml" ]; then
    echo "*** wgcf: registering a new account..."
    wgcf register --accept-tos --config /config/wgcf-account.toml
  else
    echo "*** wgcf: updating account info..."
    wgcf update --config /config/wgcf-account.toml
  fi

  if [ ! -e "/config/wgcf-profile.conf" ]; then
    echo "*** wgcf: generating a new wireguard profile..."
    wgcf generate --config /config/wgcf-account.toml --profile /config/wgcf-profile.conf
  fi

  if [ ! -e "/config/wireproxy.conf" ]; then
    cp /config/wgcf-profile.conf /config/wireproxy.conf
    echo -e "\n[Socks5]\nBindAddress = 0.0.0.0:${PROXY_PORT}" >> /config/wireproxy.conf
    if [ -n "$ENDPOINT" ]; then
      sed -i "s/engage.cloudflareclient.com/${ENDPOINT}/g" /config/wireproxy.conf
    fi
    if [ -n "$DNS" ]; then
      sed -i "s/1.1.1.1/${DNS}/g" /config/wireproxy.conf
    fi
    if [ -n "$USERNAME" ]; then
      echo -e "\nUsername = ${USERNAME}" >> /config/wireproxy.conf
    fi
    if [ -n "$PASSWORD" ]; then
      echo -e "\nPassword = ${PASSWORD}" >> /config/wireproxy.conf
    fi
  fi

  [ "${WARP_PLUS}" = "true" ] || \
    rm -f /var/run/service/svc-warp+/notification-fd
else
  rm -f /var/run/service/svc-wireproxy/notification-fd
  rm -f /var/run/service/svc-warp+/notification-fd
fi

# permissions
chown -R abc:abc \
  /config
